/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as facets from "./facets";
export * as interfaces from "./interfaces";
export { BenchmarkDiamond__factory } from "./BenchmarkDiamond__factory";
export { MockDiamond__factory } from "./MockDiamond__factory";
export { TestFacet2__factory } from "./TestFacet2__factory";
