/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BenchmarkDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BenchmarkDiamond__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet1__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet10",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet10__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet11",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet11__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet12",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet12__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet13",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet13__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet14",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet14__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet15",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet15__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet16",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet16__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet17",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet17__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet18",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet18__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet19",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet19__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet2__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet20__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet3__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet4__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet5",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet5__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet6",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet6__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet7",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet7__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet8",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet8__factory>;
    getContractFactory(
      name: "MockBenchmarkFacet9",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBenchmarkFacet9__factory>;
    getContractFactory(
      name: "MockDiamondCutFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDiamondCutFacet__factory>;
    getContractFactory(
      name: "MockDiamondLoupeFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDiamondLoupeFacet__factory>;
    getContractFactory(
      name: "MockTestFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockTestFacet__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractFactory(
      name: "MockDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDiamond__factory>;
    getContractFactory(
      name: "TestFacet2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestFacet2__factory>;

    getContractAt(
      name: "BenchmarkDiamond",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BenchmarkDiamond>;
    getContractAt(
      name: "MockBenchmarkFacet1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet1>;
    getContractAt(
      name: "MockBenchmarkFacet10",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet10>;
    getContractAt(
      name: "MockBenchmarkFacet11",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet11>;
    getContractAt(
      name: "MockBenchmarkFacet12",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet12>;
    getContractAt(
      name: "MockBenchmarkFacet13",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet13>;
    getContractAt(
      name: "MockBenchmarkFacet14",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet14>;
    getContractAt(
      name: "MockBenchmarkFacet15",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet15>;
    getContractAt(
      name: "MockBenchmarkFacet16",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet16>;
    getContractAt(
      name: "MockBenchmarkFacet17",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet17>;
    getContractAt(
      name: "MockBenchmarkFacet18",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet18>;
    getContractAt(
      name: "MockBenchmarkFacet19",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet19>;
    getContractAt(
      name: "MockBenchmarkFacet2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet2>;
    getContractAt(
      name: "MockBenchmarkFacet20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet20>;
    getContractAt(
      name: "MockBenchmarkFacet3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet3>;
    getContractAt(
      name: "MockBenchmarkFacet4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet4>;
    getContractAt(
      name: "MockBenchmarkFacet5",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet5>;
    getContractAt(
      name: "MockBenchmarkFacet6",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet6>;
    getContractAt(
      name: "MockBenchmarkFacet7",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet7>;
    getContractAt(
      name: "MockBenchmarkFacet8",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet8>;
    getContractAt(
      name: "MockBenchmarkFacet9",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBenchmarkFacet9>;
    getContractAt(
      name: "MockDiamondCutFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDiamondCutFacet>;
    getContractAt(
      name: "MockDiamondLoupeFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDiamondLoupeFacet>;
    getContractAt(
      name: "MockTestFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockTestFacet>;
    getContractAt(
      name: "IDiamondCut",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut>;
    getContractAt(
      name: "IDiamondLoupe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondLoupe>;
    getContractAt(
      name: "MockDiamond",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDiamond>;
    getContractAt(
      name: "TestFacet2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestFacet2>;

    deployContract(
      name: "BenchmarkDiamond",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BenchmarkDiamond>;
    deployContract(
      name: "MockBenchmarkFacet1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet1>;
    deployContract(
      name: "MockBenchmarkFacet10",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet10>;
    deployContract(
      name: "MockBenchmarkFacet11",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet11>;
    deployContract(
      name: "MockBenchmarkFacet12",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet12>;
    deployContract(
      name: "MockBenchmarkFacet13",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet13>;
    deployContract(
      name: "MockBenchmarkFacet14",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet14>;
    deployContract(
      name: "MockBenchmarkFacet15",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet15>;
    deployContract(
      name: "MockBenchmarkFacet16",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet16>;
    deployContract(
      name: "MockBenchmarkFacet17",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet17>;
    deployContract(
      name: "MockBenchmarkFacet18",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet18>;
    deployContract(
      name: "MockBenchmarkFacet19",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet19>;
    deployContract(
      name: "MockBenchmarkFacet2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet2>;
    deployContract(
      name: "MockBenchmarkFacet20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet20>;
    deployContract(
      name: "MockBenchmarkFacet3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet3>;
    deployContract(
      name: "MockBenchmarkFacet4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet4>;
    deployContract(
      name: "MockBenchmarkFacet5",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet5>;
    deployContract(
      name: "MockBenchmarkFacet6",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet6>;
    deployContract(
      name: "MockBenchmarkFacet7",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet7>;
    deployContract(
      name: "MockBenchmarkFacet8",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet8>;
    deployContract(
      name: "MockBenchmarkFacet9",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet9>;
    deployContract(
      name: "MockDiamondCutFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamondCutFacet>;
    deployContract(
      name: "MockDiamondLoupeFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamondLoupeFacet>;
    deployContract(
      name: "MockTestFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTestFacet>;
    deployContract(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondLoupe>;
    deployContract(
      name: "MockDiamond",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamond>;
    deployContract(
      name: "TestFacet2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFacet2>;

    deployContract(
      name: "BenchmarkDiamond",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BenchmarkDiamond>;
    deployContract(
      name: "MockBenchmarkFacet1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet1>;
    deployContract(
      name: "MockBenchmarkFacet10",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet10>;
    deployContract(
      name: "MockBenchmarkFacet11",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet11>;
    deployContract(
      name: "MockBenchmarkFacet12",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet12>;
    deployContract(
      name: "MockBenchmarkFacet13",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet13>;
    deployContract(
      name: "MockBenchmarkFacet14",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet14>;
    deployContract(
      name: "MockBenchmarkFacet15",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet15>;
    deployContract(
      name: "MockBenchmarkFacet16",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet16>;
    deployContract(
      name: "MockBenchmarkFacet17",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet17>;
    deployContract(
      name: "MockBenchmarkFacet18",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet18>;
    deployContract(
      name: "MockBenchmarkFacet19",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet19>;
    deployContract(
      name: "MockBenchmarkFacet2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet2>;
    deployContract(
      name: "MockBenchmarkFacet20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet20>;
    deployContract(
      name: "MockBenchmarkFacet3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet3>;
    deployContract(
      name: "MockBenchmarkFacet4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet4>;
    deployContract(
      name: "MockBenchmarkFacet5",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet5>;
    deployContract(
      name: "MockBenchmarkFacet6",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet6>;
    deployContract(
      name: "MockBenchmarkFacet7",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet7>;
    deployContract(
      name: "MockBenchmarkFacet8",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet8>;
    deployContract(
      name: "MockBenchmarkFacet9",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockBenchmarkFacet9>;
    deployContract(
      name: "MockDiamondCutFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamondCutFacet>;
    deployContract(
      name: "MockDiamondLoupeFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamondLoupeFacet>;
    deployContract(
      name: "MockTestFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTestFacet>;
    deployContract(
      name: "IDiamondCut",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IDiamondLoupe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondLoupe>;
    deployContract(
      name: "MockDiamond",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDiamond>;
    deployContract(
      name: "TestFacet2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestFacet2>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
